# Generated by Django 5.0.1 on 2024-01-30 21:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PP_Hidro_Cemento_Kg', models.FloatField()),
                ('PP_Hidro_Carbonato_Kg', models.FloatField()),
                ('PP_Hidro_Silice_Kg', models.FloatField()),
                ('PP_Hidro_Celulosa_Kg', models.FloatField()),
                ('PP_Hidro_Hidroxido_Kg', models.FloatField()),
                ('PP_Hidro_SolReales_porcentage', models.FloatField()),
                ('PP_Hidro_CelulosaS_porcentage', models.FloatField()),
                ('PP_Refi_EE_AMP', models.FloatField()),
                ('PP_Refi_CelulosaH_porcentage', models.FloatField()),
                ('PP_Refi_CelulosaS_porcentage', models.FloatField()),
                ('PP_Refi_CelulosaSR_SR_grados', models.FloatField()),
                ('PP_Maq_FlujoFloc_L_min', models.FloatField()),
                ('PP_Maq_Resi_ml', models.FloatField()),
                ('PP_Maq_Vueltas_N', models.IntegerField()),
                ('PP_Maq_Vel_m_min', models.FloatField()),
                ('PP_Maq_FormatoP_PSI', models.FloatField()),
                ('PP_Maq_FlujoFlocForm_L_Placa', models.FloatField()),
                ('PP_Maq_VacíoCP_PulgadasHg', models.FloatField()),
                ('PP_Maq_VacioSF_PulgadasHg', models.FloatField()),
                ('PP_Maq_Recir_porcentage', models.FloatField()),
                ('PP_Maq_Fieltro_Dias', models.IntegerField()),
                ('PP_PF_Humedad_porcentage', models.FloatField()),
                ('PP_PF_Espesor_mm', models.FloatField()),
                ('PP_PF_Dens_g_cm3', models.FloatField()),
                ('PP_Maq_FlocCanalS_porcentage', models.FloatField()),
                ('PP_Maq_FlocTkS_porcentage', models.FloatField()),
                ('PP_Maq_FlocFormS_porcentage', models.FloatField()),
                ('PP_MaqTCE_Densidad_g_cm3', models.FloatField()),
                ('PP_Maq_TCES_porcentage', models.FloatField()),
                ('PP_Maq_CilinS_porcentage', models.FloatField()),
                ('PP_Maq_Cono1S_porcentage', models.FloatField()),
                ('PP_Maq_MolinoS_porcentage', models.FloatField()),
                ('PP_Maq_P1H_porcentage', models.FloatField()),
                ('PP_Maq_P3H_porcentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.machine')),
            ],
        ),
        migrations.CreateModel(
            name='DatPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semana', models.IntegerField(blank=True, verbose_name='Semana')),
                ('Lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('registration', models.DateField(blank=True, verbose_name='registration')),
                ('registration_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='registration_date')),
                ('code_product', models.CharField(max_length=100, verbose_name='code_product')),
                ('type_product', models.CharField(max_length=100, verbose_name='type_product')),
                ('measure', models.IntegerField(verbose_name='measure')),
                ('car', models.IntegerField(verbose_name='car')),
                ('sample', models.IntegerField(verbose_name='sample')),
                ('data_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.datosmodelo')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.machine')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.process')),
                ('responsepredict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.responsepredict')),
            ],
        ),
    ]
