# Generated by Django 5.0.1 on 2024-01-31 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Separador', models.CharField(null=True)),
                ('Tallon', models.CharField(null=True)),
                ('Nudo', models.CharField(null=True)),
                ('Fisura', models.CharField(null=True)),
                ('Delaminada', models.CharField(null=True)),
                ('Desborde', models.CharField(null=True)),
                ('Ondulación', models.CharField(null=True)),
                ('Burbuja', models.CharField(null=True)),
                ('Despunte', models.CharField(null=True)),
                ('Basura', models.CharField(null=True)),
                ('Daño_Estiba', models.CharField(null=True)),
                ('Manipulación', models.CharField(null=True)),
                ('Mancha', models.CharField(null=True)),
                ('Material', models.CharField(null=True)),
                ('Rajada', models.CharField(null=True)),
                ('Desmoldeo', models.CharField(null=True)),
                ('Desmoldeadora', models.CharField(null=True)),
                ('Mal_Corte', models.CharField(null=True)),
                ('Descolgada', models.CharField(null=True)),
                ('Mal_Ondulada', models.CharField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datprediction',
            name='Semana',
        ),
        migrations.RemoveField(
            model_name='datprediction',
            name='car',
        ),
        migrations.RemoveField(
            model_name='datprediction',
            name='sample',
        ),
        migrations.AlterField(
            model_name='datprediction',
            name='Lote',
            field=models.CharField(max_length=100, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='datprediction',
            name='code_product',
            field=models.CharField(max_length=100, null=True, verbose_name='code_product'),
        ),
        migrations.AlterField(
            model_name='datprediction',
            name='measure',
            field=models.IntegerField(null=True, verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='datprediction',
            name='type_product',
            field=models.CharField(max_length=100, null=True, verbose_name='type_product'),
        ),
        migrations.AlterField(
            model_name='datprediction',
            name='responsepredict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.analysisresult'),
        ),
        migrations.DeleteModel(
            name='ResponsePredict',
        ),
    ]
