# Generated by Django 5.0.1 on 2024-01-31 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_analysisresult_remove_datprediction_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='Basura',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Burbuja',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Daño_Estiba',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Delaminada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Desborde',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Descolgada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Desmoldeadora',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Desmoldeo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Despunte',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Fisura',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Mal_Corte',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Mal_Ondulada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Mancha',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Manipulación',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Material',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Nudo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Ondulación',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Rajada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Separador',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='Tallon',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datprediction',
            name='registration',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='registration'),
        ),
    ]
